# Generated by Django 4.2.4 on 2023-09-15 14:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0006_categoryuser_category_subscribers'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['category']},
        ),
        migrations.AlterModelOptions(
            name='postcategory',
            options={'ordering': ['post']},
        ),
    ]
